### ISSUE TITLE
Row error for primary key="20193", tablet=null, server=null, status=Timed out: cannot complete before timeout

### ISSUE THREAD

**Issue by yonghaozhang** [collabH/flink-connector-kudu#10]
亲，写kudu 报了timeout，知道什么问题么，
![image](https://user-images.githubusercontent.com/10104711/131522730-883c312e-ef4b-4404-9d4b-11e89a7a089e.png)

**Comment by collabH** [comment]
ntp方面可以看看，或者谷歌下。

**Comment by yonghaozhang** [comment]
还是环境问题，，，

**Comment by vincen-zws** [comment]
老哥，请教下，我的报错和你十分相似，想请教你是怎么排查的？
