### ISSUE TITLE
unsupport operation issue

### ISSUE THREAD

**Issue by yonghaozhang** [collabH/flink-connector-kudu#11]
这个不支持的操作type=12 ,具体是什么操作，我看代码里没定义。

![image](https://user-images.githubusercontent.com/10104711/131607105-e62b5fae-c0df-4dc7-a26f-70e319cb49d0.png)
![image](https://user-images.githubusercontent.com/10104711/131607238-e2cf91ba-627f-448a-9add-0d6746bf6de0.png)

**Comment by collabH** [comment]
你怎么用的？手动穿operation的地方都是bahir自带的，我重写的一些mapper都不会关注这个operation了。

**Comment by collabH** [comment]
![image](https://user-images.githubusercontent.com/40719512/131609362-22ef9ae4-e6d0-4314-9255-5ba709e58e9c.png)

**Comment by yonghaozhang** [comment]
"CREATE TABLE `i2001__station_record_kudu` (`gas_daily_station_record_id` STRING, `gas_daily_record_id` STRING, `gas_daily_id` STRING, `supplier_type` STRING, `supplier_id` STRING, `station_code` STRING, `today_report` DOUBLE, `today_reply` DOUBLE, `yesterday_in` DOUBLE, `yesterday_out` DOUBLE, `remark` STRING, `create_user` STRING, `create_date` STRING, `modified_user` STRING, `modified_date` STRING, `is_deleted` INT) WITH('connector' = 'kudu', 'kudu.masters' = 'xxx:7051,xxxx:7051,xxxx:7051', 'kudu.table' = 'origin_ennenergy_gsm_prod.gs_ex_gas_daily_station_record_kudu', 'kudu.hash-columns' = 'gas_daily_station_record_id', 'kudu.primary-key-columns' = 'gas_daily_station_record_id')

kudu sink connector ，我根据报错日志（unknow operation）找到代码里, 不是这个类报的错么，我没太注意日志里面的类路径

**Comment by yonghaozhang** [comment]
![image](https://user-images.githubusercontent.com/10104711/131639071-43f7dba0-c743-4199-b625-568263282437.png)
这个类用到了RowDataUpsertOperationMapper --》AbstractSingleOperationMapper --》createBaseOperation

**Comment by collabH** [comment]
奇怪，RowDataUpsertOperationMapper这构造参数没有传递operation这个变量给AbstractSingleOperationMapper这个对象的，你可以本地debug一下吗，这个我还真没遇到过，并且operation是个枚举也不回打印出来type 12这个东西。。

**Comment by yonghaozhang** [comment]
![image](https://user-images.githubusercontent.com/10104711/131684355-b4eb5a38-d190-4fe4-9b34-c4ed5e5690a4.png)
type 12 是 delete ignore 操作

**Comment by yonghaozhang** [comment]
我这边kudu 版本 是 kudu-client-1.6.0-cdh5.14.4.jar， 我用的你master分支代码，kudu client 1.14 
![image](https://user-images.githubusercontent.com/10104711/131685178-1241c361-53eb-433a-9c38-7f5f584df169.png)

**Comment by collabH** [comment]
> 我这边kudu 版本 是 kudu-client-1.6.0-cdh5.14.4.jar， 我用的你master分支代码，kudu client 1.14
> ![image](https://user-images.githubusercontent.com/10104711/131685178-1241c361-53eb-433a-9c38-7f5f584df169.png)

是的，你要用tag v1.0.0版本的，改下源码kudu-client的版本

**Comment by yonghaozhang** [comment]
> > 我这边kudu 版本 是 kudu-client-1.6.0-cdh5.14.4.jar， 我用的你master分支代码，kudu client 1.14
> > ![image](https://user-images.githubusercontent.com/10104711/131685178-1241c361-53eb-433a-9c38-7f5f584df169.png)
> 
> 是的，你要用tag v1.0.0版本的，改下源码kudu-client的版本

用 tag v1.0.0版本的， 这个 kudu-client 版本1.10.0要改么，改成 1.14 么
![image](https://user-images.githubusercontent.com/10104711/131687126-dc71d35d-a0e9-4a01-af0d-42ed7c4ea547.png)

**Comment by collabH** [comment]
和你自己集群的kudu版本对其
