### ISSUE TITLE
怎么将flink1.13.xx适用的代码提交上去？

### ISSUE THREAD

**Issue by GSHF** [collabH/flink-connector-kudu#13]

**Comment by collabH** [comment]
正常提个pr即可

**Comment by GSHF** [comment]
怎么提pr呀？

**Comment by collabH** [comment]
![image](https://user-images.githubusercontent.com/40719512/143190394-409c1e5f-f7a2-4dde-84df-3b61ae02698b.png)

**Comment by collabH** [comment]
> ![image](https://user-images.githubusercontent.com/40719512/143190394-409c1e5f-f7a2-4dde-84df-3b61ae02698b.png)

建一个feature_flink_1130的分支，提下你的代码，然后我review没问题了 就可以合入

**Comment by duokaluo88** [comment]
大佬们，啥时候支持flink1.13~

**Comment by collabH** [comment]
> 大佬们，啥时候支持flink1.13~
@GSHF 找到合并的方法了吗

**Comment by collabH** [comment]
关注 #15 Issue
