### ISSUE TITLE
读取mysql-cdc的binlog数据写入kudu，timestamp类型的数据写入会少8个小时

### ISSUE THREAD

**Issue by cdjincan** [collabH/flink-connector-kudu#6]

**Comment by collabH** [comment]
这个应该是flink1.12之前的问题，他使用的时区少8小时，可以升级下flink和flink-kudu-connector的flink版本，使用timestamp_ltz类型，或者自己使用date_add函数处理一下

**Comment by cdjincan** [comment]
现在用的flink 1.13.2 ，kudu-connector内部的版本也是1.13.2，用flink内部函数current_timestamp在界面打印时时间是正确的，写kudu就少8小时

**Comment by collabH** [comment]
因为current_timestamp 1.13返回的类型是timestamp_ltz带时区的所以时间对的，你试试cdc的日期字段设置timestamp_ltz，然后设置时区`'table.local-time-zone' = 'Asia/Shanghai';`

**Comment by hnjincan** [comment]
![企业微信截图_20210813174251](https://user-images.githubusercontent.com/39942725/129528382-65de861e-5f93-42b9-b321-ff06a27f6a0d.png)
在这里加上可以用，之前flink的试了好多，还是不行

**Comment by cdjincan** [comment]
![11](https://user-images.githubusercontent.com/39942725/129528566-6d3f9246-f5e7-4767-87cb-1b0b7c10c3df.png)
在这里加上可以用，之前按照大佬你的方法设置还是不管用，这里修改下写进去就正常了

**Comment by collabH** [comment]
不过这样改后后续每个时区就固定加8小时了是不是不太好了，可以参考下flink1.13的一些connector写入的时候对timestamp ltz怎么处理的，我理解在cdc消费的时候应该就可以规定好时区，可以参考下如下sql试试：
```sql
CREATE TABLE MyTable3 (
                  item STRING,
                  price DOUBLE,
                  ts BIGINT, -- long time value in epoch milliseconds
                  ts_ltz AS TO_TIMESTAMP_LTZ(ts, 3),
                  WATERMARK FOR ts_ltz AS ts_ltz - INTERVAL '10' SECOND
            ) WITH (
                'connector' = 'socket',
                'hostname' = '127.0.0.1',
                'port' = '9999',
                'format' = 'csv'
           );
```

**Comment by collabH** [comment]
或者写入的时候可以读取下对应的时区配置，写入的时候设置好timestamp的zoneid

**Comment by cdjincan** [comment]
我现在的问题是在idea上面打印，用的print-connector时间都是正常，但是用kudu-connector，它会将我的时间减少8小时在写入kudu
![Uploading 22.png…]()

**Comment by cdjincan** [comment]
![22](https://user-images.githubusercontent.com/39942725/129534094-e8b9aea1-ba9d-4ed4-b39b-92ba6139b89f.png)

**Comment by collabH** [comment]
ok，你可以尝试改造下Kudu的DynamicSinkFactory，添加个时区配置，这样你可以在write的时候读取到配置然后设置为对应的时区写入kudu，我觉得这样也算思想和flink对齐了。
