### ISSUE TITLE
source limit push down bug

### ISSUE THREAD

**Issue by lintingbin** [collabH/flink-connector-kudu#7]
https://github.com/collabH/flink-connector-kudu/blob/8d6d9d2baaf7d167fe9f4ac2b94be9dfbc9b1dd5/src/main/java/org/colloh/flink/kudu/connector/table/source/KuduDynamicTableSource.java#L160
need be replaced by

`configBuilder = configBuilder.setRowLimit((int) limit); `

**Comment by collabH** [comment]
这个是个对象我理解不需要重新指向引用吧，并且这块我当时测试过，flink sql使用limit这段逻辑我记得是生效的。

**Comment by lintingbin** [comment]
https://github.com/collabH/flink-connector-kudu/blob/8d6d9d2baaf7d167fe9f4ac2b94be9dfbc9b1dd5/src/main/java/org/colloh/flink/kudu/connector/internal/reader/KuduReaderConfig.java#L83

你看下代码，其实是生成了一个新对象

**Comment by collabH** [comment]
已修复。
